version: '3.9'
services:
  web:
    build: ./infra/php
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
  db:
    build: ./infra/mariadb
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db-store: