version: "3.9"
services:
  web:
    build: ./infra/php
    ports:
      - 80:80
      - 9003:9003 # Xdebug
    volumes:
      - ./src:/var/www/html
  db:
    build: ./infra/mysql
    environment:
      MYSQL_ROOT_HOST : '%'
      MYSQL_ROOT_PASSWORD : password
      TZ : Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: